### PR TITLE
3DES Support

### PR DESCRIPTION
**Pull request by WingZer0o**
No need to approve this if I am totally wrong and your implementation does this as the 3DES standard. Me looking at the code I didn't believe that it did.

Due to an exercise in a book I am reading I was looking for an implementation of DES. According to Chapter 3 DES has small key size problem so 3DES was introduced. 

Three rounds of encryption are to be completed, the third either being the first 56 bit key or a brand new 56-bt key.

Looking forward to your response.

### CODE REVIEW

**Comment by antoyo** [comment]
I haven't touched this code in many years, and I'm not too familiar with 3DES.

Is this something you would want to see released? I'm asking because I do not maintain this library anymore.

**Comment by WingZer0o** [comment]
There's no need to release and I honestly didn't look at the last publis date. 

I was just following my text exercises and found this library and was oh it doesn't implement 3DES and just went ahead and coded it up as an exercise of my own.

**Comment by antoyo** [comment]
I'll close as this is not maintained anymore.

**Comment by WingZer0o** [comment]
Ah no problem, I totally forgot about this.

**Pull request closed without merging**
